# NumPy

* verwaltet effizient Arrays/Matrizen/Tensoren in `ndarray`
* ![Tensor](https://res.cloudinary.com/practicaldev/image/fetch/s--oTgfo1EL--/c_limit%2Cf_auto%2Cfl_progressive%2Cq_auto%2Cw_880/https://raw.githubusercontent.com/adhiraiyan/DeepLearningWithTF2.0/master/notebooks/figures/fig0201a.png)
* im Hintergrund hochperformantes C
* Elemente eines Arrays sind vom selben Datentyp
* Standardalias `np`
* Operationen werden meist auf ganze Arrays angewandt (*Broadcasting*)

### Vokabel

* `axis`/`axes` - Dimension
* `dtype` - Datentyp
* `shape` - Tupel, das die Form des Arrays beschreibt

In [ ]:
import numpy as np

### Erzeugung

In [ ]:
array = np.array([42, 3.1415])
print(array, array.shape, array.dtype, type(array))

[42.      3.1415] (2,) float64 <class 'numpy.ndarray'>


In [ ]:
matrix = np.arange(0, 24, 1)
print(matrix)
matrix = matrix.reshape(4, 6)
print(matrix, matrix.shape)
matrix.reshape(3, 2, 2, -1)  # -1 => was sich ausgeht

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]] (4, 6)


array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]],


       [[[16, 17],
         [18, 19]],

        [[20, 21],
         [22, 23]]]])

In [ ]:
x = np.linspace(0, np.pi, 20)  # für floats besser geeignet als arange
print(x, x.shape)
sin = np.sin(x)
print(sin)

[0.         0.16534698 0.33069396 0.49604095 0.66138793 0.82673491
 0.99208189 1.15742887 1.32277585 1.48812284 1.65346982 1.8188168
 1.98416378 2.14951076 2.31485774 2.48020473 2.64555171 2.81089869
 2.97624567 3.14159265] (20,)
[0.00000000e+00 1.64594590e-01 3.24699469e-01 4.75947393e-01
 6.14212713e-01 7.35723911e-01 8.37166478e-01 9.15773327e-01
 9.69400266e-01 9.96584493e-01 9.96584493e-01 9.69400266e-01
 9.15773327e-01 8.37166478e-01 7.35723911e-01 6.14212713e-01
 4.75947393e-01 3.24699469e-01 1.64594590e-01 1.22464680e-16]


### Ausgabe

* Arrays als []
* Matrizen als
  ```python
  [[
   []
  ]]
  ```
* Tensoren mit leerzeilen zwischen slices

In [ ]:
array = np.arange(24)
print(array)

In [ ]:
matrix = array.reshape(4, 6)
print(matrix)

In [ ]:
tensor = matrix.reshape(3, 2, 4)
print(tensor)

### Slicing

* wie bei Listen
* bei mehreren Dimensionen Indices als Tupel
* Index kann selbst Liste sein

In [ ]:
matrix = np.arange(0, 12).reshape(3, 4)
matrix = 2 ** matrix
matrix

array([[   1,    2,    4,    8],
       [  16,   32,   64,  128],
       [ 256,  512, 1024, 2048]], dtype=int32)

In [ ]:
print(matrix[1, 1])
print(matrix[1, :])
print(matrix[1])
print(matrix[:, 1])
print(matrix[::2, 0:2])
print(matrix[[1, 2], 1])

32
[ 16  32  64 128]
[ 16  32  64 128]
[  2  32 512]
[[  1   2]
 [256 512]]
[ 32 512]


### Conditional selection/Boolean indexing

* effektive filter-Methode

In [ ]:
matrix = np.arange(0, 12).reshape(3, 4)
print(matrix)
is_even = matrix % 2 == 0
print(is_even)
even_elements = matrix[is_even]
print(even_elements)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ True False  True False]
 [ True False  True False]
 [ True False  True False]]
[ 0  2  4  6  8 10]


In [ ]:
matrix[matrix > 7]

In [ ]:
a = np.random\
    .randint(30, size=10)\
    .reshape(1, -1)
a

array([[ 9, 19,  4, 15, 21,  8, 17, 26,  4, 13]])

Nützliche Funktion zum Bestimmen des Index des Maximums

In [ ]:
a.argmax()

2